const functions = require('firebase-functions');
const admin = require('firebase-admin');
const express = require('express');
const cors = require('cors');

admin.initializeApp();
const app = express();
app.use(cors({ origin: true }));
app.use(express.json());

// --- API Routes from server.ts ---

// Health check
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', source: 'firebase-functions' });
});

// Smart Email Reminder Generator
app.post('/api/generate-reminder', (req, res) => {
  try {
    const { invoice, client, businessName } = req.body;
    if (!invoice || !client) {
      return res.status(400).json({ error: 'Missing required invoice or client details' });
    }

    const currencySymbol = invoice.currency === 'USD' ? '$' : 
                            invoice.currency === 'EUR' ? '€' : 
                            invoice.currency === 'GBP' ? '£' : 
                            invoice.currency;

    const daysOverdue = invoice.dueDate ? 
      Math.floor((Date.now() - new Date(invoice.dueDate).getTime()) / (1000 * 60 * 60 * 24)) : 0;

    const subject = `Payment Reminder: Invoice ${invoice.invoiceNumber}`;
    let urgencyNote = '';
    if (daysOverdue > 30) {
      urgencyNote = 'This invoice is now over 30 days overdue. Please prioritize payment to avoid further action.';
    } else if (daysOverdue > 7) {
      urgencyNote = 'We notice this payment is overdue. Please arrange payment at your earliest convenience.';
    } else {
      urgencyNote = 'We hope you\'re satisfied with our services. Please process this payment at your convenience.';
    }

    const body = `Dear ${client.name},\n\nI hope this message finds you well.\n\nThis is a friendly reminder regarding invoice ${invoice.invoiceNumber} for ${currencySymbol}${invoice.total.toFixed(2)}, which was due on ${invoice.dueDate}.\n\n${urgencyNote}\n\nInvoice Summary:\n- Invoice Number: ${invoice.invoiceNumber}\n- Due Date: ${invoice.dueDate}\n- Amount Due: ${currencySymbol}${invoice.total.toFixed(2)}\n- Subtotal: ${currencySymbol}${invoice.subtotal.toFixed(2)}\n- Tax: ${currencySymbol}${(invoice.taxAmount || 0).toFixed(2)}\n\nIf you have already processed this payment, please disregard this reminder and accept our thanks.\n\nFor any questions or to discuss payment arrangements, please don't hesitate to contact us.\n\nBest regards,\n${businessName || 'Our Company'}\n\n---\nThis is an automated reminder generated by Invoicestack.`;

    res.json({ subject, body });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Smart Financial Insights
app.post('/api/financial-advice', (req, res) => {
  try {
    const { stats, invoicesCount, clientsCount, lowStockItems } = req.body;
    const totalRevenue = stats.totalRevenue || 0;
    const totalPaid = stats.totalPaid || 0;
    const totalOutstanding = stats.totalOutstanding || 0;
    const collectionRate = totalRevenue > 0 ? (totalPaid / totalRevenue) * 100 : 0;
    const lowStockCount = lowStockItems ? lowStockItems.length : 0;

    let summary = '';
    const recommendations = [];

    if (collectionRate >= 80) {
      summary = `Excellent cash flow health with ${collectionRate.toFixed(1)}% collection rate. Your business shows strong payment realization.`;
    } else if (collectionRate >= 60) {
      summary = `Moderate cash flow with ${collectionRate.toFixed(1)}% collection rate. Some improvement needed.`;
    } else {
      summary = `Cash flow needs attention with only ${collectionRate.toFixed(1)}% collection rate.`;
    }

    if (totalOutstanding > totalRevenue * 0.3) {
      recommendations.push('Urgent: Outstanding receivables exceed 30% of revenue.');
    }
    if (lowStockCount > 0) {
      recommendations.push(`Inventory Alert: ${lowStockCount} items are below minimum stock levels.`);
    }
    if (clientsCount < 5 && invoicesCount > 10) {
      recommendations.push('Diversification: High invoice volume with few clients increases risk.');
    }

    res.json({ summary, recommendations });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Export the app as a Cloud Function
exports.api = functions.https.onRequest(app);
