import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  app.use(express.json());

  const PORT = 3001;

  // --- API Routes ---

  // Health check endpoint
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok" });
  });

  // Smart Email Reminder Generator (template-based)
  app.post("/api/generate-reminder", async (req, res) => {
    try {
      const { invoice, client, businessName } = req.body;
      if (!invoice || !client) {
        return res.status(400).json({ error: "Missing required invoice or client details" });
      }

      const currencySymbol = invoice.currency === "USD" ? "$" : 
                            invoice.currency === "EUR" ? "€" : 
                            invoice.currency === "GBP" ? "£" : 
                            invoice.currency;

      const daysOverdue = invoice.dueDate ? 
        Math.floor((Date.now() - new Date(invoice.dueDate).getTime()) / (1000 * 60 * 60 * 24)) : 0;

      // Generate smart template-based email
      const subject = `Payment Reminder: Invoice ${invoice.invoiceNumber}`;
      
      let urgencyNote = "";
      if (daysOverdue > 30) {
        urgencyNote = "This invoice is now over 30 days overdue. Please prioritize payment to avoid further action.";
      } else if (daysOverdue > 7) {
        urgencyNote = "We notice this payment is overdue. Please arrange payment at your earliest convenience.";
      } else {
        urgencyNote = "We hope you're satisfied with our services. Please process this payment at your convenience.";
      }

      const body = `Dear ${client.name},

I hope this message finds you well.

This is a friendly reminder regarding invoice ${invoice.invoiceNumber} for ${currencySymbol}${invoice.total.toFixed(2)}, which was due on ${invoice.dueDate}.

${urgencyNote}

Invoice Summary:
- Invoice Number: ${invoice.invoiceNumber}
- Due Date: ${invoice.dueDate}
- Amount Due: ${currencySymbol}${invoice.total.toFixed(2)}
- Subtotal: ${currencySymbol}${invoice.subtotal.toFixed(2)}
- Tax: ${currencySymbol}${(invoice.taxAmount || 0).toFixed(2)}

If you have already processed this payment, please disregard this reminder and accept our thanks.

For any questions or to discuss payment arrangements, please don't hesitate to contact us.

Best regards,
${businessName || "Our Company"}
${req.body.businessEmail || ""}

---
This is an automated reminder generated by Invoicestack.`;

      res.json({ subject, body });
    } catch (error: any) {
      console.error("Error generating reminder:", error);
      res.status(500).json({ error: error.message || "Failed to generate reminder" });
    }
  });

  // Smart Financial Insights (rule-based analytics)
  app.post("/api/financial-advice", async (req, res) => {
    try {
      const { stats, invoicesCount, clientsCount, lowStockItems } = req.body;

      // Calculate key metrics
      const totalRevenue = stats.totalRevenue || 0;
      const totalPaid = stats.totalPaid || 0;
      const totalOutstanding = stats.totalOutstanding || 0;
      const collectionRate = totalRevenue > 0 ? (totalPaid / totalRevenue) * 100 : 0;
      const lowStockCount = lowStockItems ? lowStockItems.length : 0;

      // Generate smart insights based on data
      let summary = "";
      const recommendations: string[] = [];

      // Executive Summary
      if (collectionRate >= 80) {
        summary = `Excellent cash flow health with ${collectionRate.toFixed(1)}% collection rate. Your business shows strong payment realization. Focus on growth and maintaining current client relationships.`;
      } else if (collectionRate >= 60) {
        summary = `Moderate cash flow with ${collectionRate.toFixed(1)}% collection rate. Some improvement needed in payment collection processes. Review outstanding invoices and follow-up procedures.`;
      } else {
        summary = `Cash flow needs attention with only ${collectionRate.toFixed(1)}% collection rate. Immediate action required on overdue accounts. Consider implementing stricter payment terms or collection procedures.`;
      }

      // Actionable Recommendations
      if (totalOutstanding > totalRevenue * 0.3) {
        recommendations.push("**Urgent:** Outstanding receivables exceed 30% of revenue. Implement aggressive collection strategy and consider offering early payment discounts.");
      }

      if (lowStockCount > 0) {
        recommendations.push(`**Inventory Alert:** ${lowStockCount} items are below minimum stock levels. Schedule reordering to avoid stockouts and lost sales.`);
      }

      if (clientsCount < 5 && invoicesCount > 10) {
        recommendations.push("**Diversification:** High invoice volume with few clients increases risk. Focus on acquiring new clients to spread revenue risk.");
      }

      if (collectionRate < 70) {
        recommendations.push("**Payment Terms:** Review and tighten credit terms. Consider requiring deposits or shorter payment windows for new clients.");
      }

      if (totalRevenue > 0 && invoicesCount > 0) {
        const avgInvoiceValue = totalRevenue / invoicesCount;
        recommendations.push(`**Average Invoice:** $${avgInvoiceValue.toFixed(2)} per invoice. Consider upselling or bundling services to increase transaction value.`);
      }

      // Add general recommendations if none specific
      if (recommendations.length === 0) {
        recommendations.push("**Growth:** Maintain current performance. Consider expanding services or entering new markets.");
        recommendations.push("**Efficiency:** Automate invoice reminders and payment tracking to reduce administrative overhead.");
        recommendations.push("**Relationships:** Schedule regular check-ins with top clients to ensure satisfaction and identify upsell opportunities.");
      }

      res.json({
        summary,
        recommendations
      });
    } catch (error: any) {
      console.error("Error generating financial insights:", error);
      res.status(500).json({ error: error.message || "Failed to analyze financials" });
    }
  });

  // Mock Email Dispatcher
  app.post("/api/send-email", (req, res) => {
    const { to, subject, body } = req.body;
    if (!to || !subject || !body) {
      return res.status(400).json({ error: "Missing required parameter 'to', 'subject', or 'body'." });
    }

    console.log(`[EMAIL SENT] to: ${to}, subject: ${subject}`);
    res.json({ success: true, message: `Email successfully sent to ${to}` });
  });

  // --- Express Static & Vite Middleware Integration ---
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer().catch((err) => {
  console.error("Failed to boot full-stack server:", err);
});
